# Generated by Django 2.2.5 on 2019-10-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEmotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_code', models.CharField(max_length=8)),
                ('movie_title', models.CharField(max_length=128)),
                ('laugh', models.PositiveSmallIntegerField()),
                ('sad', models.PositiveSmallIntegerField()),
                ('depress', models.PositiveSmallIntegerField()),
                ('fear', models.PositiveSmallIntegerField()),
                ('lightness', models.PositiveSmallIntegerField()),
                ('heaviness', models.PositiveSmallIntegerField()),
                ('gratifying', models.PositiveSmallIntegerField()),
                ('immersion', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
